config/routes.rb
Rails.application.routes.draw do

  root controller: 'tacocopters', action: :index

  resources :tacocopters
  post 'search_tacos' => 'tacocopters#search'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :questions
end

app/models/car_wash.rb
class CarWash < ActiveRecord::Base
  #Each car wash belongs to a store
  belongs_to :stores
end

app/models/city.rb
class City < ActiveRecord::Base
  #Each city has many stores
  has_many :store
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :answers

  def output
    conn = ActiveRecord::Base.connection.raw_connection
    table = ::Text::Table.new
    conn.exec(answers.first.answer) do |result|
      table.head = result.fields
      table.rows = result.values
    end
    table.to_s
  end
end

app/models/salsa.rb
class Salsa < ActiveRecord::Base
  has_many :stores_salsa
  has_many :store, through: :stores_salsa
end

app/models/store.rb
class Store < ActiveRecord::Base
  #Has many taco stores
  has_many :stores_taco
  #Has many salsa stores
  has_many :stores_salsa
  #Has many tacos
  has_many :taco, through: :stores_taco
  #Has many salsa
  has_many :salsa, through: :stores_salsa
  #Store belongs to city (not multiple cities)
  belongs_to :city
end

app/models/stores_salsa.rb
class StoresSalsa < ActiveRecord::Base
  belongs_to :store
  belongs_to :salsa
end

app/models/stores_taco.rb
class StoresTaco < ActiveRecord::Base
  belongs_to :store
  belongs_to :taco
end

app/models/taco.rb
class Taco < ActiveRecord::Base
  has_many :stores_taco
  has_many :store, through: :stores_taco
end

app/controllers/connecting_controller.rb
class ConnectingController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions = Question.all.eager_load(:answers)
  end

end

app/controllers/schema_controller.rb
class SchemaController < ApplicationController
end

app/controllers/tacocopters_controller.rb
class TacocoptersController < ApplicationController
  before_action :set_tacocopter, only: [:show, :edit, :update, :destroy]

  # GET /tacocopters
  # GET /tacocopters.json
  def index
    # binding.pry
    @tacos = Taco.all
    @salsas = Salsa.all
    render :index
  end

  # GET /tacocopters/1
  # GET /tacocopters/1.json
  def show
    respond_to do |format|
      format.html {
        render :show
      }
      format.json { 
        render json: @results
      }
    end
  end

  # GET /tacocopters/new
  def new
    @tacocopter = Tacocopter.new
  end

  # GET /tacocopters/1/edit
  def edit
  end

  def search
    if !params[:taco].present? || !params[:salsa].present?
      redirect_to :root
      return
    end
    results = Store.includes(:taco, :salsa).where(:tacos => {:name => params[:taco]}, :salsas => {:name => params[:salsa]})
    if results.size > 0 
      results = results.order('zagat_rating desc')
    end
    @results = results
    render :show
  end

  # POST /tacocopters
  # POST /tacocopters.json
  def create
    @tacocopter = Tacocopter.new(tacocopter_params)

    respond_to do |format|
      if @tacocopter.save
        format.html { redirect_to @tacocopter, notice: 'Tacocopter was successfully created.' }
        format.json { render :show, status: :created, location: @tacocopter }
      else
        format.html { render :new }
        format.json { render json: @tacocopter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tacocopters/1
  # PATCH/PUT /tacocopters/1.json
  def update
    respond_to do |format|
      if @tacocopter.update(tacocopter_params)
        format.html { redirect_to @tacocopter, notice: 'Tacocopter was successfully updated.' }
        format.json { render :show, status: :ok, location: @tacocopter }
      else
        format.html { render :edit }
        format.json { render json: @tacocopter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tacocopters/1
  # DELETE /tacocopters/1.json
  def destroy
    @tacocopter.destroy
    respond_to do |format|
      format.html { redirect_to tacocopters_url, notice: 'Tacocopter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    #Database contains duplicate stores, return the ones with highest rating.
    def remove_duplicates(stores)
     unique = []
     stores.each do |store|

     end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_tacocopter
      @tacocopter = Tacocopter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tacocopter_params
      params[:tacocopter]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connecting_helper.rb
module ConnectingHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/schema_helper.rb
module SchemaHelper
end

app/helpers/tacocopters_helper.rb
module TacocoptersHelper
end

app/views/tacocopters/_form.html.erb
<%= form_for(@tacocopter) do |f| %>
  <% if @tacocopter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tacocopter.errors.count, "error") %> prohibited this tacocopter from being saved:</h2>

      <ul>
      <% @tacocopter.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tacocopters/edit.html.erb
<h1>Editing Tacocopter</h1>

<%= render 'form' %>

<%= link_to 'Show', @tacocopter %> |
<%= link_to 'Back', tacocopters_path %>

app/views/tacocopters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Let's eat some tacos! (They better have beer!)</h1>

<%= form_tag search_tacos_path do %>
  What kind of tacos are we in the mood for? <br /><br />
  <% @tacos.each do |taco| %>
    <%= check_box_tag 'taco[]', taco.name, false, :id => taco.id %> <%= taco.name %> <br />
  <% end %><br />

  Don't forget the salsa <br /><br />
  <% @salsas.each do |salsa| %>
  	<%= check_box_tag 'salsa[]', salsa.name, false, :id => salsa.id %> <%= salsa.name %> <br />
  <% end %><br />

  <%= submit_tag "Let's EAT!" %>
<% end %>

app/views/tacocopters/new.html.erb
<h1>New Tacocopter</h1>

<%= render 'form' %>

<%= link_to 'Back', tacocopters_path %>

app/views/tacocopters/show.html.erb
<p id="notice"><%= notice %></p>
<% if @results.size > 0 %>
  <h2>You're in luck! Found some awesome taco stores</h2>
<% else %>
  <h2>You're too picky, no tacos today :( </h2>
<% end %>
<table border="4">
	<tr>
		<th>Store</th>
		<th>City</th>
		<th>Beer</th>
		<th>Rating</th>
	</tr>
	<% @results.each do |store| %>
	  <tr>
	  	<td>
	  	  <%= store.name %>
	  	</td>
	  	<td>
	  	  <%= store.city.name %>
	  	</td>
	  	<td>
	  	  <% if store.sells_beer? %>
            Beer lunch!
	  	  <% else %>
	  	    No beer lunch..
	  	  <% end %>
	  	</td>
	  	<td> <%= store.zagat_rating %> </td>
	  </tr>
	<% end %>
</table>
<br />
<%= link_to "Search Again", :root %>